language: ruby
rvm: 2.3.3
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - tar -xf geckodriver-v0.11.1-linux64.tar.gz
  - mv geckodriver ~/.rvm/gems/ruby-2.3.3/bin
